import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit-google",
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ovo-google",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html
  lang="en" className="scroll-smooth"
>
  <body
  className={`
    ${outfit.variable}
    ${ovo.variable}
    h-full
    antialiased
    leading-8
    overflow-x-hidden
    bg-white
    text-zinc-900
    dark:bg-dark-theme
    dark:text-white
  `}
>
    {children}
  </body>
  </html>
  );
}
